### ISSUE TITLE
Feature Request - Implement Function Code "RESET_LINK_STATES"

### ISSUE THREAD

**Issue by scottyai** [gazzasaur/jdnp3#7]
New feature request to Implementation of Data Link Layer - RESET_LINK_STATES.

Additional data link function codes are required as there is no point doing a reset if CONFIRMED_USER_DATA and TEST_LINK_STATES are also implemented.

**Comment by gazzasaur** [comment]
Interesting, confirmed user data is expressly forbidden over IP (both TCP and UDP) connected devices (iirc it is because tcp and ethernet already have checksums that provide a level of integrity greater than that of these confirmations). However, given what this project is, I can totally imagine an outstation being connected over serial to Ethernet converters where these codes would be useful.

**Comment by gazzasaur** [comment]
Available in 0.12.0
